// EASY GOING
//1. Write a for loop that will log the numbers 1 through 20.
for (let i = 0;i <= 20;i++){
    console.log(i);
};
//GET EVEN
// 1. Write a `for` loop that will log only the even numbers in 0 through 200.
for (let i = 0; i <= 200; i +=2){
    console.log(i);
}

//EXCITED KITTEN
// 1. Write code that logs "Love me, pet me! HSSSSSS!" 20 times.
const catWords = ["...human...why you taking pictures of me?...","...the catnip made me do it...",
 "...why does the red dot always get away..."];

 let max = catWords.length;

//  determine how many items are in the catWords array so that you know the max number generated by your random generator

// Math.floor(Math.random() * x); 
//  ^^ this is generating a random number up to 10

// use random number generated to access a value in your array

// print that valuelet 
 

for(let i = 0; i < 20; i++){
    const random = Math.floor(Math.random() * max); 
    console.log("Love me, pet me! HSSSSSS!");
    if (i % 2 == 0){
        console.log(catWords[random]);
    }
};

//2. For every **even** number in your loop, log "...human...why you taking pictures of me?...",
// "...the catnip made me do it...", or "...why does the red dot always get away..." at random.



//FIZZ BUZZ
/*1. Write a javascript application that logs all numbers from 1 - 100.

2. If a number is divisible by 3 log "Fizz" instead of the number.

3. If a number is divisible by 5 log "Buzz" instead of the number.

4. If a number is divisible by 3 and 5 log "FizzBuzz" instead of the number.*/

for (let i = 0; i <= 100; i++){
    if  (i % 3 && i % 5 === 0){    //"FizzBuzz was not working, I fixed this by moving && condition to the top
        console.log("FizzBuzz");
     } else if (i % 5 === 0){
        console.log("Buzz");
     } else if (i % 3 === 0){
       console.log("Fizz");
     } else (console.log(i));
     };








