// EASY GOING
//1. Write a for loop that will log the numbers 1 through 20.
for (let i = 0;i <= 20;i++){
    console.log(i);
};
//GET EVEN
// 1. Write a `for` loop that will log only the even numbers in 0 through 200.
for (let i = 0; i <= 200; i +=2){
    console.log(i);
}

//EXCITED KITTEN
// 1. Write code that logs "Love me, pet me! HSSSSSS!" 20 times.
const catWords = ["...human...why you taking pictures of me?...","...the catnip made me do it...",
 "...why does the red dot always get away..."];

 let max = catWords.length;

//  determine how many items are in the catWords array so that you know the max number generated by your random generator

// Math.floor(Math.random() * x); 
//  ^^ this is generating a random number up to 10

// use random number generated to access a value in your array

// print that valuelet 
 

for(let i = 0; i < 20; i++){
    const random = Math.floor(Math.random() * max); 
    console.log("Love me, pet me! HSSSSSS!");
    if (i % 2 == 0){
        console.log(catWords[random]);
    }
};

//2. For every **even** number in your loop, log "...human...why you taking pictures of me?...",
// "...the catnip made me do it...", or "...why does the red dot always get away..." at random.





